version: '3'
services:
  node:
    image: node:latest
    volumes:
      - ./react-image-compressor:/app
    networks:
      - app-network
      
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
